name: Mean Stats

on:
  schedule:
    - cron: "52 * * * *" # every hour @ minute 52
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Cache packages  
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
    - name: Install
      run: yarn install
      
    - name: Build
      run: node index.js
      env:
        INV_LOCKED: ${{ secrets.INV_LOCKED }}
        TOTAL_TVL_URL: ${{ secrets.TOTAL_TVL_URL }}
        INTERNAL_API_URL: ${{ secrets.INTERNAL_API_URL }}
        TOKEN_ACCOUNTS_LIST: ${{ secrets.TOKEN_ACCOUNTS_LIST }}
      
    - name: Update Files
      uses: test-room-7/action-update-file@v1
      with:
          file-path: '*-stats.json'
          commit-msg: Update stats
          github-token: ${{ secrets.GITHUB_TOKEN }}
